// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package layout_views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Base() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>Go on Rails</title><!-- Primary Meta Tags --><title>Go on Rails</title><meta name=\"title\" content=\"Go on Rails\"><meta name=\"description\" content=\"A starter kit for Go, not a framework, resembling patterns found in Rails and other MVC frameworks.\"><!-- Open Graph / Facebook --><meta property=\"og:type\" content=\"website\"><meta property=\"og:url\" content=\"https://GoOnRails.com/\"><meta property=\"og:title\" content=\"Go on Rails\"><meta property=\"og:description\" content=\"A starter kit for Go, not a framework, resembling patterns found in Rails and other MVC frameworks.\"><meta property=\"og:image\" content=\"https://GoOnRails.com/glyphs.png\"><!-- Twitter --><meta property=\"twitter:card\" content=\"summary_large_image\"><meta property=\"twitter:url\" content=\"https://GoOnRails.com/\"><meta property=\"twitter:title\" content=\"Go on Rails\"><meta property=\"twitter:description\" content=\"A starter kit for Go, not a framework, resembling patterns found in Rails and other MVC frameworks.\"><meta property=\"twitter:image\" content=\"https://GoOnRails.com/glyphs.png\"><script src=\"https://cdn.tailwindcss.com?plugins=forms,typography,aspect-ratio\"></script><script defer src=\"/static/htmx.js\"></script><script defer src=\"/static/instantpage.js\" type=\"module\"></script></head><body><header><nav class=\"p-6 mx-auto\"><div class=\"flex justify-between items-center\"><a href=\"/\" class=\"text-2xl font-bold\">Go on Rails</a><div><a href=\"/login\" class=\"mr-4\">Login/Profile</a></div></div></nav></header><div class=\"p-6 mx-auto\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
